services:
  mysql:
    image: mysql:8.0
    container_name: skymanager-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root2026
      MYSQL_DATABASE: skymanager_db
      MYSQL_USER: skymanager
      MYSQL_PASSWORD: skymanager2026
    volumes:
      # Se monta la carpeta completa para que los scripts se ejecuten en orden alfabetico
      - ./init:/docker-entrypoint-initdb.d
      - skymanager_data:/var/lib/mysql

volumes:
  skymanager_data:
